name: GS-NCS
 
on: 
  workflow_dispatch:
  schedule:
    - cron: '15 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a GS-NCS
        run: |
            export TOK=${{ secrets.TOK }}
            export YOUID=${{ secrets.ID }}
            export PROGS=${{ secrets.PROGS }}
            bash ./gs-ncs
