name: GS-NC
 
on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a GS-NC
        run: |
            export TOK=${{ secrets.TOK }}
            export YOUID=${{ secrets.ID }}
            export PROG=${{ secrets.PROG }}
            bash ./gs-nc
